/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniquindio.ingesis.suturno.desktop.principal;

import java.awt.Component;

/**
 *
 * @author gusta
 */
public class PrincipalUI extends javax.swing.JFrame {

    private static final PrincipalUI ui = new PrincipalUI();
    
    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        setTitle("Programa de Turnos - Uniquindio - Laura|Gustavo");
        setBounds(0, 0, 824, 624);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbMenuPrincipal = new javax.swing.JToolBar();
        bEmpleados = new javax.swing.JButton();
        bClientes = new javax.swing.JButton();
        bServicios = new javax.swing.JButton();
        bReportes = new javax.swing.JButton();
        pContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbMenuPrincipal.setFloatable(false);
        tbMenuPrincipal.setRollover(true);

        bEmpleados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleados48.png"))); // NOI18N
        bEmpleados.setText("Empleados");
        bEmpleados.setFocusable(false);
        bEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpleadosActionPerformed(evt);
            }
        });
        tbMenuPrincipal.add(bEmpleados);

        bClientes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes48.png"))); // NOI18N
        bClientes.setText("Clientes");
        bClientes.setFocusable(false);
        bClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbMenuPrincipal.add(bClientes);

        bServicios.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/servicios48.png"))); // NOI18N
        bServicios.setText("Servicios");
        bServicios.setFocusable(false);
        bServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bServicios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServiciosActionPerformed(evt);
            }
        });
        tbMenuPrincipal.add(bServicios);

        bReportes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes48.png"))); // NOI18N
        bReportes.setText("Reportes");
        bReportes.setFocusable(false);
        bReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbMenuPrincipal.add(bReportes);

        getContentPane().add(tbMenuPrincipal);
        tbMenuPrincipal.setBounds(0, 0, 824, 92);

        pContenedor.setForeground(new java.awt.Color(255, 0, 51));
        pContenedor.setLayout(null);
        getContentPane().add(pContenedor);
        pContenedor.setBounds(12, 98, 800, 514);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpleadosActionPerformed
        cargarVentana(new EmpleadoUI());
    }//GEN-LAST:event_bEmpleadosActionPerformed

    private void bServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServiciosActionPerformed
        cargarVentana(new ServicioUI());
    }//GEN-LAST:event_bServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUI().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClientes;
    private javax.swing.JButton bEmpleados;
    private javax.swing.JButton bReportes;
    private javax.swing.JButton bServicios;
    private javax.swing.JPanel pContenedor;
    private javax.swing.JToolBar tbMenuPrincipal;
    // End of variables declaration//GEN-END:variables

    public static PrincipalUI getUi() {
        return ui;
    }
    
    
    public void cargarVentana(Component panel){
        pContenedor.removeAll();
        
        pContenedor.add(panel);
        panel.setBounds(0, 0, 800, 514);        
        
        repaint();
    }
            
    
}
